global:
  tolerations: []
  nodeSelector: {}

persistence:
  defaultClassReplicaCount: 2
  volumeBindingMode: WaitForFirstConsumer
  disableRevisionCounter: "false"

defaultSettings:
  storageOverProvisioningPercentage: "80"
  autoSalvage: "true"
  replicaAutoBalance: "best-effort"
  storageMinimalAvailablePercentage: "20"

ingress:
  enabled: true
  ingressClassName: nginx
  host: csi.lab.ashudev.in
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
